### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by meatballs** [electora-vote/whitepaper#2]
https://github.com/electora-vote/whitepaper/blob/7ccb9c9fc3b03f566e7968694c0b03a0f89fc07a/main.typ#L40

> This data aggregation facility empowers users to leverage their data across multiple platforms 

A pet hate of mine - using the noun leverage as a verb  - and here it's obfuscating any meaning (as it often does). As a mental exercise, try explaining what that sentence means and then replace this with whatever is your best effort.

**Comment by theref** [comment]
i don't understand what you're saying

**Comment by meatballs** [comment]
"empowers users to leverage their data" makes no sense. 'leverage' is a noun.

**Comment by theref** [comment]
ok got it :) it's redundant anyway, i've removed.
